export enum MovieType{
  AMOUNT_DISCOUNT = "AMOUNT_DISCOUNT",
  PERCENT_DISCOUNT = "PERCENT_DISCOUNT",
  NONE_PERCENT = "NONE_PERCENT",
}

export type TMovieType = "AMOUNT_DISCOUNT" | "PERCENT_DISCOUNT" | "NONE_PERCENT"